services:
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=todo_dev
  todo:
    build: .
    ports:
      - '5000:5000'
    command: npm start
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_DIALECT=postgres
      - DB_NAME=todo_dev
      - DB_NAME_TEST=todo_test
      - BCRYPT_SALT_ROUNDS=10
      - BCRYPT_SECRET_PEPPER=hi
      - JWT_SECRET=256bitsomethinglongsecret
      - JWT_EXPIRE=30d
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db
