services:
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
  todo:
    build: .
    ports:
      - '5000:5000'
    command: npm start
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_DIALECT=postgres
      - DB_NAME=
      - DB_NAME_TEST=
      - BCRYPT_SALT_ROUNDS=
      - BCRYPT_SECRET_PEPPER=
      - JWT_SECRET=
      - JWT_EXPIRE=
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db
